# Generated by Django 4.0.6 on 2022-07-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='id_page',
            new_name='id_tags',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='manga_offered',
            new_name='on_manga',
        ),
    ]
