# Generated by Django 4.0.6 on 2022-07-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_search', '0002_rename_id_page_tags_id_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('on-going', 'on-going'), ('hiatus', 'hiatus'), ('dropped', 'dropped')], max_length=10),
        ),
    ]
