# Generated by Django 4.0.6 on 2022-07-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_search', '0004_manga_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='on_manga',
        ),
        migrations.AddField(
            model_name='manga',
            name='tags',
            field=models.ManyToManyField(to='app_search.tags'),
        ),
    ]
