# Generated by Django 4.0.6 on 2022-07-13 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app_search', '0005_remove_tags_on_manga_manga_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='id_tags',
            new_name='id_tag',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='page',
            name='manga_offered',
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='MangaTags',
            fields=[
                ('id_manga_tag', models.BigAutoField(primary_key=True, serialize=False)),
                ('manga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_search.manga')),
                ('tags', models.ManyToManyField(to='app_search.tags')),
            ],
            managers=[
                ('tags_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MangaPages',
            fields=[
                ('id_manga_tag', models.BigAutoField(primary_key=True, serialize=False)),
                ('manga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_search.manga')),
                ('pages', models.ManyToManyField(to='app_search.page')),
            ],
            managers=[
                ('pages_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
