# Generated by Django 4.0.6 on 2022-07-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_search', '0007_manga_volumes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaHost',
            fields=[
                ('id_manga_tag', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=250)),
                ('manga', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_search.manga')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_search.page')),
            ],
        ),
    ]
