# Generated by Django 4.0.6 on 2022-07-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_search', '0008_mangahost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mangahost',
            old_name='id_manga_tag',
            new_name='id_manga_host',
        ),
    ]
