# Generated by Django 4.0.6 on 2022-07-30 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_search', '0009_rename_id_manga_tag_mangahost_id_manga_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangahost',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_search.manga'),
        ),
    ]
