# Generated by Django 4.0.6 on 2022-07-30 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_search', '0010_alter_mangahost_manga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangahost',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_search.page'),
        ),
    ]
