# Generated by Django 4.0.6 on 2022-07-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id_submission', models.BigAutoField(primary_key=True, serialize=False)),
                ('problem', models.CharField(choices=[(0, 'submit page / manga'), (1, 'report a problem')], max_length=1)),
                ('manga_name', models.CharField(max_length=40)),
                ('page_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=400)),
            ],
        ),
    ]
